### ISSUE TITLE
How to send HTML?

### ISSUE THREAD

**Issue by jwinnie** [Odi-ts/odi#59]
I have the following code in a controller:

    @RouteGet("/hey") sayHello() {
        return `<h1>Hey!</h1>`
    }

But the return type is `text/plain`. How do I make the return type `text/html`?

**Comment by DanTsk** [comment]
Fixed in c888c90bd13a3f9da674e054c584bce1b9e88d27, just update odi to `0.2.13` version. And call the method in handler.

Example:
```typescript
@RouteGet("/hey")
sayHello() {
    this.setType('text/html');

    return `<h1>Hey!</h1>`
}
```

In next major release ([0.3.0](https://github.com/Odi-ts/odi/milestone/1)) templates rendering functional will be added.
