### ISSUE TITLE
GrahpQl feature release

### ISSUE THREAD

**Issue by jld3103** [Odi-ts/odi#70]
I'd really love to use Odi for a new project, but I decided to use GraphQl as DB and this feature is currently not supported. Is it possible to give a hint on the release date? Would be nice.

**Comment by DanTsk** [comment]
Hi! Thanks a lot for your interest!
Currently, there will be a small refactoring of WebSockets and Repositories. After that, we will work on SSR improvements and GraphQL. So it can take up to 1-2 weeks for release.

**Comment by jld3103** [comment]
Thanks for your quick response! 1-2 weeks is totally ok for me, because I need to plan my project first. Thanks!
