### ISSUE TITLE
Error using query decorator

### ISSUE THREAD

**Issue by chimon2000** [Odi-ts/odi#89]
I get the following error when attempting to use a query decorator:

```bash
Error: schema is invalid: data.properties['required'] should be object, boolean
```

Here is the example query:

```ts
import { Query, IsRequired } from "odi";

@Query()
export class GreetingQueryDto {
  @IsRequired() name: string;
}

```

**Comment by DanTsk** [comment]
Hi! It seems that **fastify** changed schema processing for `quertstring`. 
Now it's fixed. Just update Odi to the lastest version - **0.3.53**

Thanks for pointing!
